/**
 * Bundled FDS schemas v1.3.0
 *
 * GENERATED by scripts/build-schemas.mjs — do not edit.
 * Run `npm run build:schemas` from the repository root.
 *
 * These are byte-identical copies of the published schemas, bundled so the
 * transformer can validate without a network round trip.
 */

import exerciseSchema from './exercise.schema.json' assert { type: 'json' };
import equipmentSchema from './equipment.schema.json' assert { type: 'json' };
import muscleSchema from './muscle.schema.json' assert { type: 'json' };
import muscleCategorySchema from './muscle-category.schema.json' assert { type: 'json' };
import bodyAtlasSchema from './body-atlas.schema.json' assert { type: 'json' };
import workoutSchema from './workout.schema.json' assert { type: 'json' };
import programSchema from './program.schema.json' assert { type: 'json' };

/**
 * Entity versions this release is composed of. Entities version independently,
 * so a release names a *set* of entity versions rather than one shared segment.
 */
export const entityVersions = {
  exercise: '1.1.0',
  equipment: '1.1.0',
  muscle: '1.0.0',
  'muscle-category': '1.0.0',
  'body-atlas': '1.0.0',
  workout: '1.0.0',
  program: '1.0.0',
} as const;

export default {
  exercise: exerciseSchema,
  equipment: equipmentSchema,
  muscle: muscleSchema,
  'muscle-category': muscleCategorySchema,
  'body-atlas': bodyAtlasSchema,
  workout: workoutSchema,
  program: programSchema,
};

export {
  exerciseSchema,
  equipmentSchema,
  muscleSchema,
  muscleCategorySchema,
  bodyAtlasSchema,
  workoutSchema,
  programSchema,
};
