/**
 * FDS releases and the entity versions each one names.
 *
 * GENERATED by scripts/build-schemas.mjs from specification/releases.json —
 * do not edit. Run `npm run build:schemas` from the repository root.
 *
 * A release is a *set* of entity versions rather than one path segment they all
 * share: 1.4.0 serves exercise, equipment and workout at 1.1.0 while muscle,
 * muscle-category, body-atlas and program stay at 1.0.0. Expanding a release
 * name into a path segment requests URLs that were never published.
 *
 * Definition libraries are absent by construction. `prescription` publishes
 * alongside these entities but validates nothing, so there is no document to
 * fetch it for.
 */

/** The newest published release. */
export const CURRENT_RELEASE = '1.4.0';

/** Entity schema versions per release. */
export const RELEASE_ENTITY_VERSIONS: Record<string, Record<string, string>> = {
  '1.0.0': {
    exercise: '1.0.0',
    equipment: '1.0.0',
    muscle: '1.0.0',
    'muscle-category': '1.0.0',
    'body-atlas': '1.0.0',
  },
  '1.1.0': {
    exercise: '1.1.0',
    equipment: '1.1.0',
    muscle: '1.0.0',
    'muscle-category': '1.0.0',
    'body-atlas': '1.0.0',
  },
  '1.2.0': {
    exercise: '1.1.0',
    equipment: '1.1.0',
    muscle: '1.0.0',
    'muscle-category': '1.0.0',
    'body-atlas': '1.0.0',
    workout: '1.0.0',
  },
  '1.3.0': {
    exercise: '1.1.0',
    equipment: '1.1.0',
    muscle: '1.0.0',
    'muscle-category': '1.0.0',
    'body-atlas': '1.0.0',
    workout: '1.0.0',
    program: '1.0.0',
  },
  '1.4.0': {
    exercise: '1.1.0',
    equipment: '1.1.0',
    muscle: '1.0.0',
    'muscle-category': '1.0.0',
    'body-atlas': '1.0.0',
    workout: '1.1.0',
    program: '1.0.0',
  },
};
