import { describe, it, expect } from 'vitest';
import {
  DEFAULT_SCHEMA_VERSION,
  RELEASE_ENTITY_VERSIONS,
  entityVersionFor,
} from './versions.js';
import {
  CURRENT_RELEASE,
  RELEASE_ENTITY_VERSIONS as GENERATED_RELEASE_ENTITY_VERSIONS,
} from './releases.generated.js';
import { SchemaManager } from './schema-manager.js';

/**
 * Entities version independently, so a release name is not a path segment.
 * Getting that wrong is silent: every entity 404s, the loader falls back to
 * bundled, and the transformer runs offline forever without saying so.
 *
 * Both the map and the bundled schemas are generated by
 * `scripts/build-schemas.mjs` from the published tree, so these tests check the
 * map against the `$id` the generator wrote — the version an implementer would
 * actually have to fetch.
 *
 * Every release is covered because the set of releases is read from the map
 * itself rather than listed here. A hand-written list of releases to test is a
 * list that goes stale, and it went stale exactly once: 1.4.0 shipped as the
 * newest release and was the only one whose version map nothing checked.
 */

/**
 * The bundled copies for a release.
 *
 * `index.ts`, not `index.js`, because the specifier is a variable: Vite resolves
 * a dynamic import like this one by globbing the literal path on disk, and the
 * extension rewrite that makes `./x.js` find `x.ts` does not apply. The package
 * itself cannot import bundles this way — a bundler needs static specifiers,
 * which is why `schema-manager.ts` keeps one loader per release — but a test is
 * never bundled, so here it can ask for the releases the map declares instead of
 * for the ones somebody remembered to import.
 */
const bundleFor = async (release: string): Promise<Record<string, unknown>> => {
  const module = await import(`./bundled/v${release}/index.ts`);
  return (module.default ?? module) as Record<string, unknown>;
};

const RELEASES = Object.keys(RELEASE_ENTITY_VERSIONS).sort();

const versionFromId = (schema: unknown): string => {
  const id = (schema as { $id?: string }).$id ?? '';
  const match = id.match(/\/v(\d+\.\d+\.\d+)\/[^/]+\.schema\.json$/);
  if (!match) throw new Error(`no version in $id: ${id || '(missing)'}`);
  return match[1];
};

describe('release versioning', () => {
  /**
   * The map is generated from `specification/releases.json`, and
   * `npm run check:schemas` fails when the generated file and the manifest
   * disagree. That only holds while this module re-exports it: a hand-written
   * copy here would shadow the generated one and nothing outside this package
   * would notice.
   */
  describe('the facts come from the generated manifest', () => {
    it('re-exports the generated map rather than restating it', () => {
      expect(RELEASE_ENTITY_VERSIONS).toBe(GENERATED_RELEASE_ENTITY_VERSIONS);
    });

    it('defaults to the generated current release', () => {
      expect(DEFAULT_SCHEMA_VERSION).toBe(CURRENT_RELEASE);
    });
  });

  describe('entityVersionFor', () => {
    it('maps each entity of a known release to the version it published', () => {
      expect(entityVersionFor('exercise', '1.1.0')).toBe('1.1.0');
      expect(entityVersionFor('equipment', '1.1.0')).toBe('1.1.0');
      // unchanged in 1.1.0 — must keep their 1.0.0 URLs
      expect(entityVersionFor('muscle', '1.1.0')).toBe('1.0.0');
      expect(entityVersionFor('muscle-category', '1.1.0')).toBe('1.0.0');
      expect(entityVersionFor('body-atlas', '1.1.0')).toBe('1.0.0');
    });

    it('falls back to the release itself for a release it has never heard of', () => {
      // Keeps an older transformer able to fetch a newer published release.
      expect(entityVersionFor('exercise', '2.0.0')).toBe('2.0.0');
      expect(entityVersionFor('muscle', '2.0.0')).toBe('2.0.0');
    });

    it('falls back for an unknown entity within a known release', () => {
      expect(entityVersionFor('workout', '1.1.0')).toBe('1.1.0');
    });
  });

  describe('the map agrees with the bundled schemas it describes', () => {
    it.each(RELEASES)('release %s', async (release) => {
      const bundle = await bundleFor(release);
      const declared = RELEASE_ENTITY_VERSIONS[release];

      // Both directions. An entity added to the bundle but not the map would be
      // fetched from a URL built off the release name; one added to the map but
      // not the bundle would 404 remotely and have no offline copy to fall back
      // to. Either way the failure is silent at runtime.
      expect(Object.keys(bundle).sort()).toEqual(Object.keys(declared).sort());

      for (const [entity, version] of Object.entries(declared)) {
        expect(versionFromId(bundle[entity]), `${release}/${entity} $id`).toBe(version);
      }
    });
  });

  describe('DEFAULT_SCHEMA_VERSION', () => {
    it('names the newest release', () => {
      expect(DEFAULT_SCHEMA_VERSION).toBe(RELEASES.at(-1));
    });

    it('is bundled, so the default path works offline', () => {
      expect(SchemaManager.hasBundledVersion(DEFAULT_SCHEMA_VERSION)).toBe(true);
    });
  });

  /**
   * Publishing a version without bundling it is the failure the offline
   * fallback exists to survive: the fetch 404s, the fallback throws, and (before
   * the fix) validation passed everything. Every release the manifest names must
   * have a loader in `schema-manager.ts`, which is still one hand-written entry
   * per release.
   */
  describe('every known release is bundled', () => {
    it('has no release without an offline copy', () => {
      expect(SchemaManager.getBundledVersions()).toEqual(RELEASES);
    });
  });
});
